apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: llama-3-1-8b-instruct
  namespace: kubeai
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  features:
    - TextGeneration
  owner: meta-llama  
  url: "hf://meta-llama/Llama-3.1-8B-Instruct"
  engine: VLLM
  resourceProfile: doks-nvidia:1
  args:
    - --max-model-len=8192
    - --gpu-memory-utilization=0.9
  minReplicas: 1
  maxReplicas: 1
